name: Web Scraper

on:
  schedule:
    - cron: "0 0 */15 * *"
  push:
    branches:
      - main

jobs:
  run_scraper:
    runs-on: csson
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl urllib3 beautifulsoup4 Pyarrow

    - name: Run Web Scraper
      run: python fiis/main.py

    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: excel file
        path: fiis.xlsx
